### ISSUE TITLE
Not Optimal enough

### ISSUE THREAD

**Issue by skippy369** [OptimalBit/optimalbit.github.io#1]
Please fix ASAP

**Comment by benswift404** [comment]
Just no. LOL.

**Comment by benswift404** [comment]
Dustin

**Comment by skippy369** [comment]
Hello, world

**Comment by benswift404** [comment]
class Greeter
  attr_accessor :name
  def initialize(name = "World")
    @name = name
  end

  def hi
    puts "Hello, #{@name}!"
  end

  def bye
    puts "Bye #{@name}, come back soon!"
  end
end

**Comment by skippy369** [comment]
hi

**Comment by benswift404** [comment]
whats up
